apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-helloworld
  namespace: default
  labels:
    app: maven-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-helloworld
  template:
    metadata:
      labels:
        app: maven-helloworld
    spec:
      containers:
      - name: maven-helloworld
        image: dxb.ocir.io/axgucdgtb9mk/hello-world:v1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registrypullsecret
