apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
  labels:
    app: maven-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-helloworld
  template:
    metadata:
      labels:
        app: maven-helloworld
    spec:
      containers:
      - name: maven-helloworld
        image: test/hello-world
        ports:
        - containerPort: 3000
