apiVersion: v1
kind: Service
metadata:
  name: maven-helloworld
  namespace: default
spec:
  selector:
    app: maven-helloworld
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
